### ISSUE TITLE
PDF生成処理の作成と公開

### ISSUE THREAD

**Issue by KengoTODA** [Tokyo-Metro-Gov/tokyo-oss-guideline#10]
このリポジトリの目的が記載されていないため推測の域を出ませんが、おそらくは第三者による再利用も視野に入れての公開だと予想しています。その場合、テキストを変更した第三者が「PDFを再生成したい」というニーズを持つ可能性は高いと思われます。

以上の理由から、PDF生成処理の作成と公開を検討されてはいかがでしょうか。継続的統合を行う意味でも、PDF生成処理の作成と公開、ないし可能ならばGitHub Actionsでの自動実行を行うことも視野に入れたほうが良いと思います。

ご利用のツールがわからないので役に立つか不明ですが、参考までに私の[Honkit](https://github.com/honkit/honkit)を使って[PDF生成しているGitHub Actions Workflow](https://github.com/KengoTODA/what-is-maven/blob/591f5e77f8229385e26b40f623c0ed708215f037/.github/workflows/build.yml)を共有します。将来的に多言語翻訳も構想に入っているのであれば、[Sphinx](https://www.sphinx-doc.org/en/master/)や[Docusaurus](https://docusaurus.io/)なども検討して良いかもしれません。

**Comment by tmatsuno** [comment]
ご提案ありがとうございます。
現在のところPDF版については、都庁内で展開されるWord版から生成する形としているため、マークダウンをマスタとする計画はありません。
よって、自動生成は現在のところ、検討から外れております。
