### ISSUE TITLE
README.md と LICENSE.md ファイルはできるだけ早く置くべきだと思います。

### ISSUE THREAD

**Issue by mapconcierge** [Tokyo-Metro-Gov/tokyo-oss-guideline#2]
README.md と LICENSE.md ファイルはできるだけ早く置くべきだと思います。

**Comment by KengoTODA** [comment]
同意見ですが、もう少し理由についても述べてみます。

`README.md`ファイルがないと、このリポジトリがどういった目的で作成し公開されているのかがわかりません。単なる文書の置き場なのか、意見や貢献を受け付けて文書を改善する場なのか、COVIDウェブサイトのように第三者がforkし再利用することまで意識しているのかなど、いくつかの可能性が考えられますが、こうした意図をこのリポジトリ内にある文面で示すことでそれを伝えることができます。また文書の著作権者を明確にすることも、後述するライセンスを適用する上で重要になります。

`LICENSE`ファイルがないと、どのようなライセンスが適用されるのかがわかりません。これが明確でないと、貢献も再利用もしにくいのは事実としてあると思います。また頒布側としても、再利用において制限がかけられないのでは、公開の目的を達成できないということもあるかもしれません。

以上です。

**Comment by tmatsuno** [comment]
ライセンスですが、今回回公開しているものはソースコードではなく、ガイドラインの類になりますが、どのようなライセンス形態をとることが多いか、ご存じでしたらご教示いただけますと幸いです。

**Comment by tmatsuno** [comment]
readme.mdについては、現在内容を検討中となっています。しばらくお待ちください。

**Comment by KengoTODA** [comment]
> ソースコードではなく、ガイドラインの類になりますが、どのようなライセンス形態をとることが多いか、ご存じでしたらご教示いただけますと幸いです。

普遍的で良い問いだと思ったので、掘り下げた説明を[ブログに書いてみました](https://blog.kengo-toda.jp/entry/2021/11/02/101134)。よろしければご参照ください。

結論だけ述べるなら、Creative Commonsが多いようです。[Creative Commonsのchoose a licenseページ](https://creativecommons.org/choose/)を参照して、目的にあったCreative Commons 4.0ライセンスを選ばれると良いと思います。

**Comment by mapconcierge** [comment]
Chooselicense.com サイトから選ぶのが良いと思いますが
https://choosealicense.com/non-software/

個人的には CC0 を推奨します。
https://choosealicense.com/licenses/cc0-1.0/

**Comment by tmatsuno** [comment]
取り急ぎ、[README.md](https://github.com/Tokyo-Metro-Gov/tokyo-oss-guideline/blob/main/README.md) を追加しました。
ライセンスについては内部で検討を続けているため、もう少々お待ちください。

**Comment by HIroyukiS43** [comment]
ライセンスについて、都庁内で議論しています。
議論の中で、このガイドラインを”利用される方の目的”が何かがライセンスの選択の根拠になるのではないかと考えています。

この考えから、ますは、利用目的が何かを想定してみました。
１　東京都のガイドラインだから、コピーしたい。（信頼性の確保）
２　ガイドラインを作る手間を省きたい。（作業の効率化）

この２つの理由をもとに、次のようにライセンスを想定してみました。
1の場合であれば、信頼性を確保するためにCCby4.0
2の場合であれば、できる限り利用しやすくCC0

どちらが良いのか、正直、迷ってます。ご意見をいただければ幸いです。

**Comment by hfu** [comment]
「信頼性を確保」する目的で CC-BY を選択されるとすれば、それは「信頼性を保証」しようとされているという意味になると思います。それは都庁さんにとり、割と重いコミットをされるという意味になるように思います。

東京都の信頼を用いたいユーザの方は、ライセンスによる出所明示義務を負わなくとも、東京都のブランドに適正に言及されることと思いますので、「信頼性を確保するために」という理由であれば CC-BY である必要はなく、よって「できる限り利用しやすく」という理由が優って CC0 という結論になるのではないか、と思いました。

CC-BY を選択することにより、あたかも東京都がガイドラインの内容を「保証をする」かのような誤解を与えやすくなる、という指摘でございました。

**Comment by HIroyukiS43** [comment]
早速のアドバイスありがとうございます。
他にもご意見があればぜひお聞かせください。

**Comment by KengoTODA** [comment]
> １　東京都のガイドラインだから、コピーしたい。（信頼性の確保）

私としては、都のアウトプットだから信頼するというよりは、都のアウトプットだから前例として扱いやすいという方が想像しやすいです。企業や団体とは少し事情が違う、他の道府県や自治体が参考にする前例としてわかりやすいということですね。ので信頼性の担保はあまり重要ではないように思います。

またhfuさんの指摘されている「保証をする」ように受け取られるのも問題です。が、CC0にしろCCby4.0にしろ無保証が基本なので、それらを選ぶことで「都が保証する」ことにはなりません。誤解を招くコミュニケーションを取らないよう注意すれば大丈夫だと思います。

**Comment by KengoTODA** [comment]
CCby4.0のCC0に対する利点は、再頒布者がクレジットを表示することにより、再頒布された成果物の利用者にも出どころ（upstream）にアクセスする手段が提供されることだと思います。

例えばとある県でガイドラインを再頒布し、更にその内容に疑問を感じた利用者がいた場合。その利用者は「県に変更を訴える」だけでなく「都に変更を訴えて、その実績を持って県にアプローチをかける」選択肢が取れるようになります。都から見れば、再頒布先での事例や知見を自身のガイドラインに反映し成長を加速できるということです。

まぁ、果たしてそこまでする利用者がどこまでいるのかという話は別にありますが。

**Comment by HIroyukiS43** [comment]
アドバイス、ありがとうございます。
実効果は別として、CCby4.0を採用することで、都にもメリットがあるということが理解できました。もう少し他の事例も調べつつ、ライセンスを設定したいと思います。
